version: "3.7"

volumes:
  mongo_data:

services:
  all_moscow:
    build:
      context: .
    restart: always
    command: python3 AllMoscow.py
    volumes:
      - .:/source
    depends_on:
      - mongo
      - rabbit
  main:
    build:
      context: .
    restart: always
    command: python3 BotTelegram.py
    volumes:
      - .:/source
    depends_on:
      - mongo
      - rabbit
  parser:
    build:
      context: .
    restart: always
    command: python3 CianParserMain.py
    volumes:
      - .:/source
    depends_on:
      - mongo
      - rabbit
  updates_manager:
    build:
      context: .
    restart: always
    command: python3 UpdatesManagerMain.py
    volumes:
      - .:/source
    depends_on:
      - mongo
      - rabbit
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo_data:/data/db
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=telegram_realty_admin
      - RABBITMQ_DEFAULT_PASS=realty_da_best
